name: Build Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Windows
          combine: true
